@baseUrl = http://localhost:5925
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNkYzM5NGJjLWNjOGQtNGZhMS1iODkwLWE3YTUwOWFlN2UzZSIsIkZ1bGxOYW1lIjoiTMOqIFRow6BuaCBMb25nIiwiUm9sZUlkIjoiOTBiNTU5NWUtOTZhMC00MzJkLWEwNTAtODVmOTY0ZDk5ZDIzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NzU4MDEyNjksImlzcyI6ImNvbnRhaW5lci1hcHAiLCJhdWQiOiJjb250YWluZXItY2xpZW50In0.LLDS-SdHL3pRx35SeuwJBnyB1Bm4FYe1r5mdRx5oD5Y
### Login
POST {{baseUrl}}/api/login
Content-Type: application/json
{
  "username": "longlt",
  "password": "123"
}

### Insert-User
POST {{baseUrl}}/api/insert-user
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Username": "mynk",
  "Password": "123",
  "Fullname": "Nguyễn Kha My",
  "Phone": "0236988547",
  "Email": "mynguyen@gomicorp.vn",
  "Address": "Quy Nhơn, Bình Định",
  "CreateBy": null,
  "RoleId": "60FDFF12-400E-4BA5-9891-D7DB4716E2DB"
}

### Insert-KhachSan
POST {{baseUrl}}/api/khachsan/tao
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "TenKhachSan": "Quê Hương Hotel",
  "MoTa": "Homstay ở Bình Định, ở trung tâm thành Phố Quy Nhơn, cách eo gió 10p đi xe",
  "DiaChi": "10A Trần Cao Vân, Quy Nhơn, Bình Định",
  "ThanhPho": "Quy Nhơn",
  "ViDo": 11.1835617,
  "KinhDo": 106.2612741,
  "SoSao": 3,
  "GioNhanPhong": "14:00",
  "GioTraPhong": "12:00",
  "TrangThai": "cho_duyet"
}

### Thêm Tiện Ích
POST {{baseUrl}}/api/tienich/tao
Content-Type: application/json
{
  "TenTienIch": "WIFI 24/7",
  "Icon": "<i class=\"fa-solid fa-wifi\"></i>"
}

### Thêm Loại Phòng
POST {{baseUrl}}/api/loaiphong/tao
Content-Type: application/json
{
  "KhachSanId": "43DB82C5-1719-4E21-99A2-3FA278C19CCF",
  "TenLoaiPhong": "Phòng Đơn",
  "SoKhachToiDa": 2,
  "KieuGiuong": "Giường đơn",
  "MoTa": "Phòng đôi rộng rãi phù hợp cặp đôi, đầy đủ tiện nghi."
}

### Thêm Phòng
POST {{baseUrl}}/api/phong/tao
Content-Type: application/json
{
  "LoaiPhongId": "841D6A63-B470-4BE6-9011-6E916CE1DB7D",
  "SoPhong": "01",
  "Tang": 1,
  "TrangThai": "san_sang"
}


### Lấy danh sách khách sạn
POST {{baseUrl}}/api/khachsans/get
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Keyword": null,
  "ThanhPho": null,
  "ViDo": null,
  "KinhDo": null,
  "SoSao": 0,
  "TrangThai": null,
  "Page": 1
}